#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Suvi
{
using System;

#line 2 "Complete.cshtml"
using System.Collections.Generic;

#line default
#line hidden
using System.Linq;
using System.Text;

#line 1 "Complete.cshtml"
using Suvi.Data;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Complete : System.Web.Mvc.WebViewPage<Suvi.Data.Survey>
{

#line hidden

public override void Execute()
{
WriteLiteral("<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral("\n      xmlns:fb=\"http://ogp.me/ns/fb#\"");

WriteLiteral(">\n<head>\n  \n  <title>Survey in Pocket</title>\n  <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(">\n  <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"Content/bootstrap.min.css\"");

WriteLiteral(" />\n  <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"Content/font-awesome.min.css\"");

WriteLiteral(" />\n  <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"Content/application.css\"");

WriteLiteral(" />\n  <script");

WriteLiteral(" src=\"Scripts/jquery-2.1.4.min.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\n  <script");

WriteLiteral(" src=\"Scripts/frontend.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\n");


#line 16 "Complete.cshtml"
  

#line default
#line hidden

#line 16 "Complete.cshtml"
   if (ViewData.ContainsKey("CustomCss") && ViewData["CustomCss"] != null){

  	foreach(var css in (List<string>)ViewData["CustomCss"]){


#line default
#line hidden
WriteLiteral("  \t\t <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute ("href", " href=\"", "\""

#line 19 "Complete.cshtml"
, Tuple.Create<string,object,bool> ("", css

#line default
#line hidden
, false)
);
WriteLiteral(" />\n");


#line 20 "Complete.cshtml"
  	}
  }


#line default
#line hidden
WriteLiteral("</head>\n<body>\n");


#line 24 "Complete.cshtml"
Write(Html.Partial("Suvi.Header, Suvi", null));


#line default
#line hidden
WriteLiteral("\n\n<main>\n<div");

WriteLiteral(" class=\"container-fluid feedback-container\"");

WriteLiteral(">\n\n<article");

WriteLiteral(" class=\"page question-page widget\"");

WriteLiteral(">\n\t<div");

WriteLiteral(" class=\"widget-extra\"");

WriteLiteral(" >\n\n\t\t<div");

WriteLiteral(" class=\"widget-content-light question-title ty-title\"");

WriteLiteral(">\n\t\t\tThank you!\n\t\t</div>\n\t  <h4");

WriteLiteral(" class=\"widget-content-light question-content\"");

WriteLiteral(">\n\n\t\t<p");

WriteLiteral(" class=\"description-content\"");

WriteLiteral("></p>\n\t  </h4>\n\t</div>\n</article>\n\n</div>\n</main>\n</body>\n</html>");

}
}
}
#pragma warning restore 1591
