#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Suvi
{
using System;

#line 2 "Header.cshtml"
using System.Collections.Generic;

#line default
#line hidden
using System.Linq;
using System.Text;

#line 1 "Header.cshtml"
using Suvi.Data;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Header : System.Web.Mvc.WebViewPage<Suvi.Data.Question>
{

#line hidden

public override void Execute()
{
WriteLiteral("<header");

WriteLiteral(" class=\"global-header\"");

WriteLiteral(">\n  <div");

WriteLiteral(" class=\"container-fluid clearfix title-bar\"");

WriteLiteral(">\n\t<div class = \"col-xs-2 logo-container\">\n\t\t\n\t</div>\t\n    <nav");

WriteLiteral(" class=\"header-nav col-xs-10\"");

WriteLiteral(">\n      <div");

WriteLiteral(" class=\"header-link active survey-name\"");

WriteLiteral(">\n");


#line 12 "Header.cshtml"
      	

#line default
#line hidden

#line 12 "Header.cshtml"
         if(Model != null &&  Model.Survey != null){


#line default
#line hidden
WriteLiteral("        \t<span>");


#line 13 "Header.cshtml"
             Write(Model.Survey.Name);


#line default
#line hidden
WriteLiteral("</span>\n");


#line 14 "Header.cshtml"
        }


#line default
#line hidden
WriteLiteral("      </div>\n\t          \n        <strong><span");

WriteLiteral(" class=\"text question-order\"");

WriteLiteral(" id=\"order\"");

WriteLiteral("></span></strong>\n    </nav>\n  </div>\n\n</header>\n<div");

WriteLiteral(" class=\"feedback-progress clearfix\"");

WriteLiteral(">\n  <div");

WriteLiteral(" class=\"svipk-progress pull-left\"");

WriteLiteral("></div>\n</div>\n\n");

}
}
}
#pragma warning restore 1591
