#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Suvi
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "SmileyFace.cshtml"
using Suvi.Data;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class SmileyFace : System.Web.Mvc.WebViewPage<Suvi.Data.Question>
{

#line hidden

public override void Execute()
{
WriteLiteral("<div");

WriteLiteral(" class=\"question-smiley-faces\"");

WriteLiteral(">\n  <span");

WriteLiteral(" class=\"question-faces\"");

WriteLiteral(">\n");


#line 6 "SmileyFace.cshtml"
        

#line default
#line hidden

#line 6 "SmileyFace.cshtml"
         for(var i=1; i<=4; i++)
        {


#line default
#line hidden
WriteLiteral("\t        <div class = \"col-xs-3 smiley-block\">\n\t            <label");

WriteLiteral(" class=\"smiley-face\"");

WriteAttribute ("for", " for=\"", "\""

#line 9 "SmileyFace.cshtml"
          , Tuple.Create<string,object,bool> ("", Model.ID + '-' + i

#line default
#line hidden
, false)
);
WriteLiteral(">\n\t              <input");

WriteLiteral(" class=\"smiley-radio\"");

WriteLiteral(" type=\"radio\"");

WriteAttribute ("value", " value=\"", "\""

#line 10 "SmileyFace.cshtml"
                           , Tuple.Create<string,object,bool> ("", i

#line default
#line hidden
, false)
);
WriteAttribute ("id", " id=\"", "\""

#line 10 "SmileyFace.cshtml"
                                    , Tuple.Create<string,object,bool> ("", Model.ID + '-' + i

#line default
#line hidden
, false)
);
WriteAttribute ("name", " name=\"", "\""
, Tuple.Create<string,object,bool> ("", "question[", true)

#line 10 "SmileyFace.cshtml"
                                                                         , Tuple.Create<string,object,bool> ("", Model.Index

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "]", true)
);
WriteLiteral(">\n\t              <img");

WriteAttribute ("src", " src=\'", "\'"

#line 11 "SmileyFace.cshtml"
, Tuple.Create<string,object,bool> ("", "Content/Images/SmileyFaces/" + i + ".png"

#line default
#line hidden
, false)
);
WriteLiteral("/>\n\t            </label>\n\t        </div>\n");


#line 14 "SmileyFace.cshtml"
        }


#line default
#line hidden
WriteLiteral("  </span>\n</div>\n\n");

}
}
}
#pragma warning restore 1591
